### PR TITLE
reduced number of colors and changed homepage image

### PR DESCRIPTION
**Pull request by llwasampijja**
Hello People,
This is my latest UI code with the recommended changes. Please take some time to review and leave back some feedback and advice, Thanks.

@3Nakajugo  @stephencmwanika  @bashman1  @NicholusMuwonge   @66hakeem   @Phionanamugga  @engjames  @Paphra  @digit2018  @BrunoNicholas  @edrinesolo  @astonetuhame  @jngisiro  @Hassan-Ssemanda  @Emmanuelaaron  @alexxsanya  @dkato8181   @AbuDeCoder  @Nico-Nsereko  @alinitweSandra  @daspro1503  @ivankfit   @ asimwec  @brucenelm  @sebbss  @Rhytah  @JamesMudidi  @musasizifrancis  @RachealN  @nearjay06  @mderek227  @sanya-kenneth   @neelxie   @frankopkusianwar  @AtamaZack    @ManuelDominic  @KabohaJeanMark    @mwinel  @chrismatgit   @ringtho  @nadralia  @Kwandera  @JammyKalungi  @reifred   @jennizalwango @jkMugabe   @richien  @araali1  @Mastula77   @Genza999  @wabuluka  @noahkalyesubula  @lizz24   @kalsmic   @k7ko  @bekeplar  @e-ian   @masete  @Manorlds-Eaglespark  @nanfuka   @HarrietAkot  @PatrickMugayaJoel  @kyakusahmed   @Anguandia   @CandySusan   @kabaliisa @bisonlou  @HabibSentongo   @v1b3m  @kdenno   @davicken  @dtnnml  @Araali1  @natalie-abbie @ernesthenry

### CODE REVIEW

**Comment by Rhytah** [comment]
Great work, the UIs are interactive and smooth. 
However, I would recommend making use of one background image that isn't so busy with detail, it is distracting to the eye. 
Also when making use of lighter hues of background colour, it is better to contrast and use darker font colours and vice versa.
Try restricting access to the admin panel as well.

Great job.

**Comment by Emmanuelaaron** [comment]
Wow great work, To add on what Rytah has recommended, please try to correct the spelling of silent other than sillent.

**Comment by 3Nakajugo** [comment]
Good work. I like the app responsiveness

**Review by JamesMudidi — COMMENTED** [review]
To add on what everyone has already said, try to make use of colour contrast like when a user hovers over a menu item or link the menu item or link should remain visible to the user

**Comment by llwasampijja** [comment]
> Great work, the UIs are interactive and smooth.
> However, I would recommend making use of one background image that isn't so busy with detail, it is distracting to the eye.
> Also when making use of lighter hues of background colour, it is better to contrast and use darker font colours and vice versa.
> Try restricting access to the admin panel as well.
> 
> Great job.

Thank you @Rhytah for your feedback, highly appreciate it. about the Image, do you think if I remove some of the people, will the image work?

**Comment by llwasampijja** [comment]
> To add on what everyone has already said, try to make use of colour contrast like when a user hovers over a menu item or link the menu item or link should remain visible to the user

Thanks a lot @JamesMudidi let me fix that,

**Comment by llwasampijja** [comment]
> Good work. I like the app responsiveness

Thanks a lot @3Nakajugo I highly appreciate your feedback

**Comment by llwasampijja** [comment]
> Wow great work, To add on what Rytah has recommended, please try to correct the spelling of silent other than sillent.

Thanks @Emmanuelaaron, I highly value your feedback. Let me fix this ASAP!

**Comment by ghost** [comment]
- I think the user should not  access other pages before signing in or up,try working on it, try making the search field responsive also

**Comment by llwasampijja** [comment]
> * I think the user should not  access other pages before signing in or up,try working on it, try making the search field responsive also

Thanks a lot @Phionanamugga. I will work on that!

**Comment by mwinel** [comment]
- There is a dropdown menu that has logout and yet you have the signout in navbar, choose which one of the two.
- There is also need to separate roles, meaning the admin panel should only be visible by the admin.
- Thanks for adding the deployment link, this makes peoples review so much easier and faster.

**Comment by llwasampijja** [comment]
> * There is a dropdown menu that has logout and yet you have the signout in navbar, choose which one of the two.
> * There is also need to separate roles, meaning the admin panel should only be visible by the admin.
> * Thanks for adding the deployment link, this makes peoples review so much easier and faster.

Thanks a bunch @mwinel . Let me work on this ASAP

**Comment by nearjay06** [comment]
This looks ok..just work on responsiveness and media queries

**Pull request merged**
